name: mlflow_demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.5
  - notebook=6.5.4
  - jupyterlab=3.6.3
  - jupyter_core=5.3.0
  - numba=0.57.1
  - pandas=1.5.3
  - pip=23.2.1
  - scikit-learn=1.3.0
  - openpyxl=3.0.10
  - cookiecutter 1.7.3
  - pyyaml=6.0
  - mlflow=2.7.1
  - hydra-core=1.3.2
  - pip:
      - hydra-joblib-launcher==1.2.0
