main:
  project_name: pipeline_demo
  experiment_name: demo

input:
  text: Hello World
  artifact_name: processed_text_artifact
  artifact_type: text
  artifact_description: Processed text data example

output:
  text: Bye World
