main:
  project_name: "workflow_demo"
  experiment_name: "run_in_n_out"

input:
  text: "##### Hello from the config input section! ####"

output:
  add_text: "##### Hello from the config output section! ####"
